import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/About";
import BackgroundCircles from "../components/BackgroundCircles";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Skills from "../components/Skills";
import WorkExperience from "../components/WorkExperience";
import { hanieData } from "../asset/data";
import ContactMe from "../components/ContactMe";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div
      className="text-white h-screen snap-y snap-mandatory overflow-y-scroll z-0 overflow-x-hidden
       scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]/80"
      style={{
        backgroundColor: hanieData.backgroundColor,
      }}
    >
      <Head>
        <title>{hanieData.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section id="hero" className="snap-start">
        <Hero />
      </section>
      <section id="about" className="snap-center">
        <About />
      </section>
      <section id="experience" className="snap-center">
        <WorkExperience />
      </section>
      <section id="skills" className="snap-start">
        <Skills />
      </section>
      <section id="projects" className="snap-start">
        <Projects />
      </section>
      <section id="contact" className="snap-start">
        <ContactMe />
      </section>
      <Link href="#hero">
        <footer className="sticky bottom-5 w-full cursor-pointer">
          <div className="flex items-center justify-center">
            <img
              className="h-10 w-10 rounded-full filter grayscale hover:grayscale-0 cursor-pointer"
              src="https://avatars.githubusercontent.com/u/69413612?s=96&v=4"
              alt="mh"
            />
          </div>
        </footer>
      </Link>
    </div>
  );
};

export default Home;
